import type { Metadata } from "next";
import { Sedan_SC, Montserrat } from 'next/font/google'
import "./globals.css";

const sedanSC = Sedan_SC ({
  subsets: ['latin'],
  weight: '400'
});

const montserrat = Montserrat ({
  subsets: ['latin'],
  weight: 'variable'
});

export const metadata: Metadata = {
  title: "DawgWallet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
          <link href="https://fonts.googleapis.com/css2?family=Sedan+SC:wght@700&display=swap" rel="stylesheet" />
        </head>
      <body>
        {children}
      </body>
    </html>
  );
}
